### ISSUE TITLE
Hello, do you know how to hide Momo detection developer mode and adb debugging

### ISSUE THREAD

**Issue by df13954** [rushiranpise/Hide-Debugging#1]

**Comment by rushiranpise** [comment]
no,not able to bypass momo, it will detect injection

**Comment by df13954** [comment]
> no,not able to bypass momo, it will detect injection

After my analysis, I do not believe it is an injection situation. The modification of attributes is based on the system, which means that my ROM supports attribute modification and the functions in Settings have added logs. Obviously, no logs were found, and he does not use the functions in Settings.
